### ISSUE TITLE
error in the install docs: new Dniccum\CustomEmailSender\CustomEmailSender(),

### ISSUE THREAD

**Issue by jayenne** [dniccum/nova-custom-email-sender#11]
Hi, you havea small error on the installaction doc.

you should add the namespace to the tools() too....
new Dniccum\CustomEmailSender\CustomEmailSender(),

**Comment by dniccum** [comment]
Thanks for the heads up. Addressed in [v1.1.0](https://github.com/dniccum/nova-custom-email-sender/tree/v1.1.0)
