### ISSUE TITLE
send email to other users

### ISSUE THREAD

**Issue by kenkaigu** [dniccum/nova-custom-email-sender#14]
By default, nova has a users resource. i assume , if you click on ( send to all users) , it sends from this particular resource==>  users table.

if you have a customers resource  or customers table with email addresses
Is it possible to send emails to all the emails found in customer table?

**Comment by dniccum** [comment]
Yes, you can indicate which model that you would like to send messages to within the configuration file, [see this line]( https://github.com/dniccum/nova-custom-email-sender/blob/979316693514b3a95064cc017bdcf0446122f938/config/novaemailsender.php#L53), as well as the columns that you would like to use for their name.
