### ISSUE TITLE
Preview fails with custom template/ markdown option is turned off

### ISSUE THREAD

**Issue by sonofascoby** [dniccum/nova-custom-email-sender#27]
When using a custom template (placed in  ```resources/views/vendor/custom-email-sender/email.blade.php```) **and** turning off the markdown option in the config the preview no longer works. The following appears - [https://jmp.sh/Mqb2nhP](https://jmp.sh/Mqb2nhP)

**Comment by dniccum** [comment]
This will be fixed in the next release #31
