### ISSUE TITLE
Option to disable inline css Quill styling/ formatting

### ISSUE THREAD

**Issue by sonofascoby** [dniccum/nova-custom-email-sender#28]
Would it be possible to have an option to disable inline styling for the email messages?

I have a custom template that styles h1,2,p tags etc but this is ignored as the Quill editor adds its own inline styling  - https://jmp.sh/IlPnNmn

**Comment by dniccum** [comment]
Unfortunately this treatment is being implemented by Laravel's default [CSS injection](https://laravel.com/docs/8.x/mail#customizing-the-css); which is ultimately the best way to send email addresses. The Quill editor is pretty stripped down as it is

If you are having issues, I would recommend modifying the `default.css` mail theme file.
