### ISSUE TITLE
Duplicated email preview when changing pages

### ISSUE THREAD

**Issue by Uriyah3** [dniccum/nova-custom-email-sender#34]
When I preview an email, then change to a different Nova component (Users resource for example), then go back to this tool and write another email, the preview is duplicated (attached an image for context). For each change I do to a different Nova component, another duplicated preview appears. It doesn't affect the emails that are sent though, only the preview. Also, when I manually refresh the page it fixes itself.

I tested this on both the last release (v2.1.0) and the current master branch.

![image](https://user-images.githubusercontent.com/20377934/101350781-547d7c00-386e-11eb-8fe9-ef16fcae1e72.png)

**Comment by dniccum** [comment]
Yep, I am seeing this as well. I am in the final stages of wrapping up Version 3 (on the master branch), so I will push the fix there.

**Comment by dniccum** [comment]
I addressed this in version 3.0.0
