### ISSUE TITLE
Feature request: make an extractor from custom table for mailto users

### ISSUE THREAD

**Issue by phoenixg** [dniccum/nova-custom-email-sender#4]

**Comment by dniccum** [comment]
Could you be more specific as to what you are looking for?

**Comment by phoenixg** [comment]
The sendto multi input box is only useful for several emails, what if I want to send to hundreds of emails that would be unconvenient, so I hope there is a extractor which support custom search criterial  for my email list.

**Comment by dniccum** [comment]
Addressed in [v1.1.0](https://github.com/dniccum/nova-custom-email-sender/tree/v1.1.0)
