### ISSUE TITLE
Select query is not using config

### ISSUE THREAD

**Issue by andreasbergqvist** [dniccum/nova-custom-email-sender#9]
See:
https://github.com/dniccum/nova-custom-email-sender/blob/master/src/Library/UserUtility.php#L59

Shouldn't the select query use the config?

In my case I don't have any name columns on the user. I would want to use 'email' for both email and name.

PR incoming

**Comment by dniccum** [comment]
Fixed in [release v1.0.3](https://github.com/dniccum/nova-custom-email-sender/tree/v1.0.3)
